-- Cas du simulateur de consultation, parcours lombaire.
--
-- Vingt patients pour dix-sept feuilles de l'arbre de décision : chaque
-- conduite possible est jouable, et les trois orientations en urgence sont
-- représentées par trois tableaux différents, parce que c'est là que
-- l'erreur coûte le plus cher.
--
-- Un cas ne décrit que ce qu'il a d'anormal à l'examen. Les examens non
-- mentionnés renvoient le résultat normal du catalogue (lib/region-simulation.ts),
-- ce qui garde les cas lisibles et évite les « sans particularité » absurdes.

DO $do$
DECLARE
  v_module UUID;
  v_noeuds JSONB;
  v_orphelin TEXT;
BEGIN
  SELECT id INTO v_module FROM public.region_modules WHERE slug = 'lombaire';
  IF v_module IS NULL THEN
    RAISE EXCEPTION 'Module lombaire absent';
  END IF;

  DELETE FROM public.region_simulation_cases WHERE module_id = v_module;

  INSERT INTO public.region_simulation_cases
    (module_id, slug, label, difficulty, presentation, secret, exams, expected, debrief, order_index)
  VALUES

  -- 1. Queue de cheval ------------------------------------------------------
  (v_module, 'queue-de-cheval', $t$Syndrome de la queue de cheval$t$, 'decouverte',
   $j${"prenom":"Damien","age":42,"sexe":"homme","profession":"magasinier","motif":"Blocage lombaire depuis trois jours, avec une douleur qui descend maintenant dans les deux jambes","contexte":"Il est venu en boitant et reste debout dans la salle d’attente"}$j$::jsonb,
   $j${"histoire":"Lombalgie brutale il y a trois jours en soulevant une palette. Hier soir, la douleur est descendue dans les deux cuisses, et depuis ce matin il a du mal à uriner : il sent l’envie mais rien ne vient, ou très peu.","douleur":"Lombaire basse, 8 sur 10, avec des décharges dans les deux jambes jusqu’aux mollets.","aggravants":"La position assise, la toux.","soulageants":"Rien vraiment. Debout c’est un peu moins pire.","antecedents":"Deux lumbagos sans gravité. Pas de maladie connue, pas de traitement.","drapeaux":"Il a remarqué depuis ce matin que la peau entre les cuisses et autour de l’anus est comme endormie, un peu comme après une anesthésie chez le dentiste. Il n’en parle pas de lui-même parce qu’il trouve cela gênant. Il a uriné pour la dernière fois hier soir.","vecu":"Il pense que c’est un nerf coincé et veut se faire craquer le dos pour pouvoir retourner travailler lundi.","a_ne_pas_dire_spontanement":"Les troubles urinaires et l’engourdissement du périnée ne sortent que si on pose la question, même indirectement."}$j$::jsonb,
   $j${"perine":"Rétention urinaire depuis la veille au soir avec mictions par regorgement. Hypoesthésie en selle franche et bilatérale. Tonus anal ressenti comme diminué par le patient.","neuro_force":"Fléchisseurs plantaires cotés à 4 sur 5 des deux côtés, extension des orteils à 4 sur 5 à gauche.","neuro_reflexes":"Réflexes achilléens abolis des deux côtés.","neuro_sensibilite":"Hypoesthésie des deux faces postérieures de cuisse et de la région périnéale.","slr":"Positif des deux côtés à 40 degrés, avec reproduction de la douleur habituelle.","mobilite_active":"Toutes les amplitudes limitées par la douleur, patient en attitude antalgique."}$j$::jsonb,
   $j${"issue":"fin_urgence","tableau":"Syndrome de la queue de cheval, forme rétentionnelle","elements":["Sciatalgie devenue bilatérale en quelques heures","Difficulté mictionnelle apparue le matin même","Hypoesthésie en selle"],"examens_cles":["perine","neuro_force","neuro_sensibilite"],"piege":"Le patient demande une manipulation et parle d’un simple nerf coincé. Le motif affiché est un blocage lombaire banal."}$j$::jsonb,
   $t$Le seul dépistage qui tranche ici tient en trois questions, et aucune n’est posée spontanément par le patient : miction, selles, sensibilité périnéale. La récupération sphinctérienne dépend du délai de décompression, ce qui fait de ce tableau la seule vraie urgence horaire de la consultation lombaire.$t$, 1),

  -- 2. Fracture ostéoporotique ---------------------------------------------
  (v_module, 'fracture-osteoporotique', $t$Fracture vertébrale ostéoporotique$t$, 'decouverte',
   $j${"prenom":"Colette","age":74,"sexe":"femme","profession":"retraitée, ancienne institutrice","motif":"Douleur brutale du bas du dos depuis huit jours, apparue en soulevant un sac de terreau","contexte":"Elle se déplace doucement et cherche un appui pour s’asseoir"}$j$::jsonb,
   $j${"histoire":"Douleur apparue d’un coup il y a huit jours en soulevant un sac de terreau de dix kilos. Depuis, elle ne cède pas et elle est réveillée dès qu’elle change de position la nuit.","douleur":"En ceinture, très basse dans le dos, 7 sur 10, sans irradiation dans les jambes.","aggravants":"Se redresser depuis la position assise, marcher, tousser.","soulageants":"Rester allongée sur le dos sans bouger.","antecedents":"Traitée par corticoïdes depuis deux ans pour une pseudo-polyarthrite rhizomélique. Ménopause à 48 ans, pas de traitement osseux. Elle a perdu quatre centimètres de taille en dix ans, ce qu’elle attribue à l’âge.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer connu. Elle prend de la cortisone tous les jours.","vecu":"Elle craint de finir immobilisée et veut surtout être rassurée.","a_ne_pas_dire_spontanement":"La corticothérapie et la perte de taille ne sont mentionnées que si on interroge les traitements ou les antécédents."}$j$::jsonb,
   $j${"palpation_epineuses":"Point exquis reproductible sur l’épineuse de L1, percussion douloureuse au même niveau, contracture paravertébrale réactionnelle.","mobilite_active":"Extension et redressement très douloureux, flexion limitée par la douleur, pas d’irradiation.","drapeaux_rouges":"Âge supérieur à 70 ans, corticothérapie prolongée, perte de taille de quatre centimètres, douleur d’apparition brutale sur un effort modeste.","imagerie":"Indication retenue : radiographies du rachis dorsolombaire de face et de profil, à demander par le médecin traitant."}$j$::jsonb,
   $j${"issue":"fin_avis_rapide","tableau":"Fracture vertébrale ostéoporotique de L1","elements":["Traumatisme minime chez une patiente de plus de 70 ans","Corticothérapie prolongée","Perte de taille","Point exquis et percussion douloureuse sur une épineuse"],"examens_cles":["drapeaux_rouges","palpation_epineuses"],"piege":"Le mécanisme, un sac de terreau, ressemble à celui d’un lumbago. C’est le terrain qui change tout."}$j$::jsonb,
   $t$Une fracture ostéoporotique ne se présente pas comme un traumatisme : elle se présente comme un lumbago chez quelqu’un dont l’os ne supporte plus un effort ordinaire. La corticothérapie prolongée, la perte de taille et l’âge forment le faisceau, et aucun de ces trois éléments n’est dit spontanément.$t$, 2),

  -- 3. Métastase osseuse ----------------------------------------------------
  (v_module, 'metastase', $t$Douleur rachidienne d’origine tumorale$t$, 'intermediaire',
   $j${"prenom":"Gérard","age":68,"sexe":"homme","profession":"retraité, ancien chauffeur routier","motif":"Douleur lombaire qui s’installe depuis deux mois et ne passe pas","contexte":"Il a été adressé par son kinésithérapeute, qui n’obtient pas de résultat"}$j$::jsonb,
   $j${"histoire":"Douleur apparue sans cause il y a deux mois, d’aggravation progressive. Elle le réveille maintenant toutes les nuits vers trois heures, et il finit la nuit dans le fauteuil.","douleur":"Lombaire haute, sourde, permanente, 6 sur 10 le jour et davantage la nuit.","aggravants":"Rien de net, elle est là tout le temps.","soulageants":"Le paracétamol ne fait plus rien. Aucune position ne la calme vraiment.","antecedents":"Adénocarcinome de la prostate traité il y a six ans, suivi espacé, il n’y pense plus. Hypertension.","drapeaux":"Il a perdu environ six kilos depuis le printemps sans faire de régime. Pas de fièvre. Fatigue inhabituelle.","vecu":"Il dit que son kiné lui a trouvé un blocage et il vient chercher un autre avis.","a_ne_pas_dire_spontanement":"Le cancer de la prostate et la perte de poids ne sortent que si on interroge les antécédents et l’état général."}$j$::jsonb,
   $j${"drapeaux_rouges":"Antécédent de cancer de la prostate, perte de six kilos en quatre mois, douleur nocturne non soulagée par le décubitus, âge supérieur à 50 ans.","mobilite_active":"Amplitudes conservées et peu douloureuses, sans rapport avec l’intensité de la plainte.","palpation_epineuses":"Sensibilité diffuse de la région lombaire haute, sans point exquis franc.","imagerie":"Indication retenue devant le faisceau de drapeaux rouges : à demander par le médecin, sans attendre."}$j$::jsonb,
   $j${"issue":"fin_avis_rapide","tableau":"Suspicion de localisation secondaire rachidienne","elements":["Antécédent de cancer","Perte de poids inexpliquée","Douleur nocturne non soulagée par le repos","Discordance entre une plainte forte et un examen mécanique pauvre"],"examens_cles":["drapeaux_rouges","mobilite_active"],"piege":"Le patient a déjà un diagnostic dans la tête, celui de son kinésithérapeute, et il oriente la consultation vers un blocage."}$j$::jsonb,
   $t$L’antécédent de cancer est le seul drapeau rouge dont la valeur isolée est établie. Ici il vient avec deux autres éléments, et la discordance entre l’intensité de la plainte et la pauvreté de l’examen mécanique est le signal que le tableau n’est pas musculosquelettique.$t$, 3),

  -- 4. Spondylodiscite ------------------------------------------------------
  (v_module, 'spondylodiscite', $t$Spondylodiscite infectieuse$t$, 'expert',
   $j${"prenom":"Michel","age":57,"sexe":"homme","profession":"artisan plombier","motif":"Douleur lombaire depuis trois semaines, de plus en plus forte","contexte":"Il transpire et paraît fatigué"}$j$::jsonb,
   $j${"histoire":"Douleur installée progressivement il y a trois semaines, sans effort déclenchant. Elle augmente de jour en jour et il dort très mal.","douleur":"Lombaire médiane, permanente, 7 sur 10, présente au repos comme au mouvement.","aggravants":"Tout, et surtout la nuit.","soulageants":"Rien. Les anti-inflammatoires de sa pharmacie n’ont rien changé.","antecedents":"Diabète de type 2 traité. Une infiltration lombaire il y a six semaines pour une sciatique. Une infection urinaire traitée il y a un mois.","drapeaux":"Il a des sueurs nocturnes et se sent fiévreux par moments, sans avoir pris sa température. Pas de perte de poids notable.","vecu":"Il veut reprendre les chantiers et pense qu’un bon massage le remettrait d’aplomb.","a_ne_pas_dire_spontanement":"L’infiltration récente, le diabète et les sueurs nocturnes ne sortent que si on interroge les antécédents et l’état général."}$j$::jsonb,
   $j${"constantes":"Température à 38,4 degrés. Patient pâle, sueurs. Tension dans les normes.","drapeaux_rouges":"Fièvre, sueurs nocturnes, geste rachidien invasif récent, diabète, douleur permanente non mécanique d’aggravation progressive.","palpation_epineuses":"Douleur exquise à la percussion des épineuses de L3 et L4, contracture paravertébrale majeure.","mobilite_active":"Raideur globale majeure, toute mobilisation est douloureuse."}$j$::jsonb,
   $j${"issue":"fin_urgence","tableau":"Spondylodiscite infectieuse","elements":["Douleur permanente d’aggravation progressive","Fièvre et sueurs nocturnes","Geste rachidien invasif récent","Terrain diabétique"],"examens_cles":["constantes","drapeaux_rouges","palpation_epineuses"],"piege":"Prendre la température n’est pas un réflexe en thérapie manuelle. Sans ce geste, le tableau ressemble à une lombalgie rebelle."}$j$::jsonb,
   $t$Prendre une température fait partie de l’examen quand la douleur est permanente et progressive. Le faisceau est ici complet : geste invasif récent, terrain diabétique, fièvre, douleur qui ne cède en aucune position. C’est une orientation immédiate, pas un avis à programmer.$t$, 4),

  -- 5. Spondyloarthrite axiale ---------------------------------------------
  (v_module, 'spondyloarthrite', $t$Spondyloarthrite axiale$t$, 'intermediaire',
   $j${"prenom":"Yanis","age":27,"sexe":"homme","profession":"développeur informatique","motif":"Mal de dos depuis deux ans, mis sur le compte de la position assise","contexte":"Il pratique la course à pied et se dit en bonne forme"}$j$::jsonb,
   $j${"histoire":"Douleurs lombaires et fessières depuis environ deux ans, installées progressivement, avec des périodes plus calmes. Il met cela sur le compte du bureau.","douleur":"Lombaire basse et fessière, alternant d’un côté à l’autre, 5 sur 10.","aggravants":"Le repos, l’inactivité, les longs trajets. C’est le matin que c’est le pire.","soulageants":"Bouger, courir, la douche chaude. Les anti-inflammatoires le soulagent remarquablement bien.","antecedents":"Un psoriasis du cuir chevelu qu’il traite par shampooing. Une inflammation de l’oeil il y a trois ans, traitée par un ophtalmologue. Son père a une spondylarthrite ankylosante.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer. Il se réveille vers quatre heures du matin à cause du dos et doit se lever pour se dégourdir. Le dérouillage matinal dure plus d’une heure.","vecu":"Il pense avoir une mauvaise posture et vient chercher des conseils d’ergonomie.","a_ne_pas_dire_spontanement":"Le psoriasis, l’uvéite et l’antécédent familial ne sortent que si on interroge précisément les antécédents personnels et familiaux."}$j$::jsonb,
   $j${"rythme_inflammatoire":"Quatre critères ASAS sur cinq : début avant 40 ans, installation progressive, amélioration par l’exercice, douleur nocturne de seconde partie de nuit. Dérouillage matinal supérieur à une heure.","schober":"Schober à 3,5 cm, ampliation thoracique à 3 cm : les deux diminués.","cluster_laslett":"Deux tests sur cinq reproduisent une douleur fessière, sans les deux tests de compression et de thigh thrust conjointement.","mobilite_active":"Raideur en fin d’amplitude dans tous les plans, plus marquée le matin selon le patient."}$j$::jsonb,
   $j${"issue":"fin_rhumato","tableau":"Spondyloarthrite axiale","elements":["Rachialgie de rythme inflammatoire chez un homme de moins de 40 ans","Réveil de seconde partie de nuit et dérouillage de plus d’une heure","Réponse remarquable aux anti-inflammatoires","Psoriasis, uvéite et antécédent familial"],"examens_cles":["rythme_inflammatoire","schober"],"piege":"Le patient est jeune, sportif, et attribue tout à sa posture. Deux ans de thérapie manuelle sans interroger le rythme de la douleur, c’est le scénario habituel."}$j$::jsonb,
   $t$Le délai diagnostique de la spondyloarthrite axiale se compte encore en années, et ces patients passent ce temps chez des thérapeutes manuels. La question qui tranche est gratuite : est-ce que la douleur vous réveille en seconde partie de nuit, et combien de temps met-elle à se dérouiller le matin ?$t$, 5),

  -- 6. Anévrisme de l'aorte abdominale -------------------------------------
  (v_module, 'anevrisme', $t$Anévrisme de l’aorte abdominale$t$, 'expert',
   $j${"prenom":"Robert","age":71,"sexe":"homme","profession":"retraité, ancien agriculteur","motif":"Douleur lombaire apparue il y a dix jours, qu’il n’avait jamais eue","contexte":"Gros fumeur, il parle d’une douleur qui lui prend le ventre et le dos"}$j$::jsonb,
   $j${"histoire":"Douleur installée il y a une dizaine de jours, sans effort. Elle ne ressemble à aucun de ses maux de dos habituels.","douleur":"Lombaire et en avant, comme un battement profond dans le ventre, 6 sur 10, permanente.","aggravants":"Rien de particulier, elle va et vient toute seule.","soulageants":"Aucune position ne la change, ni allongé, ni debout, ni assis.","antecedents":"Hypertension, tabac depuis l’âge de seize ans, cholestérol. Son frère a été opéré de l’aorte.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer.","vecu":"Il dit que sa femme l’a poussé à venir et qu’il n’aime pas les médecins.","a_ne_pas_dire_spontanement":"Le caractère battant de la douleur et l’antécédent familial ne sortent que si on demande précisément comment la douleur se manifeste et ce qu’il y a dans la famille."}$j$::jsonb,
   $j${"pouls":"Masse abdominale battante et expansive palpée en région péri-ombilicale. Pouls fémoraux perçus, pouls pédieux diminués des deux côtés.","mobilite_active":"Amplitudes complètes et indolores : aucun mouvement ne reproduit la douleur.","palpation_epineuses":"Palpation rachidienne indolore.","constantes":"Apyrétique, tension à 165 sur 95."}$j$::jsonb,
   $j${"issue":"fin_urgence","tableau":"Anévrisme de l’aorte abdominale","elements":["Douleur lombaire nouvelle chez un homme de plus de 65 ans, tabagique et hypertendu","Douleur qu’aucune position ne modifie","Examen rachidien strictement normal","Masse abdominale battante"],"examens_cles":["pouls","mobilite_active"],"piege":"Palper l’abdomen n’entre pas dans l’examen habituel d’une lombalgie. Sans ce geste, le tableau reste une lombalgie non spécifique du sujet âgé."}$j$::jsonb,
   $t$Une douleur lombaire qu’aucune position ne modifie, chez un homme de plus de 65 ans, tabagique, avec un examen rachidien normal : ce faisceau impose de palper l’abdomen et de prendre les pouls. C’est un geste de dix secondes, et c’est le seul qui fasse la différence entre une consultation banale et une urgence vitale.$t$, 6),

  -- 7. Douleur non mécanique d'origine viscérale ---------------------------
  (v_module, 'viscerale', $t$Douleur projetée d’origine viscérale$t$, 'intermediaire',
   $j${"prenom":"Nadia","age":44,"sexe":"femme","profession":"aide-soignante","motif":"Douleur du bas du dos à droite depuis trois semaines","contexte":"Elle porte des patients toute la journée et pense à un faux mouvement"}$j$::jsonb,
   $j${"histoire":"Douleur apparue il y a trois semaines, sans effort identifié. Elle vient par crises de une à deux heures, très fortes, puis s’apaise.","douleur":"Lombaire droite haute, irradiant parfois vers l’épaule droite et le flanc, 8 sur 10 pendant les crises.","aggravants":"Souvent une à deux heures après un repas riche. Rien à voir avec les efforts ou les positions.","soulageants":"Rien. Elle tourne dans la maison pendant les crises sans trouver de position.","antecedents":"Deux grossesses. Surpoids. Pas de traitement.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer. Quelques nausées pendant les crises.","vecu":"Elle veut qu’on lui débloque la côte, comme la dernière fois.","a_ne_pas_dire_spontanement":"Le lien avec les repas et les nausées ne sortent que si on demande ce qui déclenche les crises et ce qui les accompagne."}$j$::jsonb,
   $j${"mobilite_active":"Toutes les amplitudes sont libres et indolores, aucune ne reproduit la douleur.","palpation_epineuses":"Palpation rachidienne et costale indolore, pas de reproduction de la douleur habituelle.","pa_segmentaires":"Pressions segmentaires indolores et sans reproduction.","constantes":"Apyrétique, état général conservé.","drapeaux_rouges":"Aucun drapeau rouge rachidien retrouvé."}$j$::jsonb,
   $j${"issue":"fin_non_mecanique","tableau":"Douleur projetée d’origine biliaire","elements":["Douleur par crises, rythmée par les repas et non par les mouvements","Aucune position antalgique","Examen rachidien strictement normal et non reproducteur","Nausées associées"],"examens_cles":["mobilite_active","palpation_epineuses"],"piege":"La patiente demande un geste précis et a déjà une explication mécanique. Il faut accepter de ne rien trouver plutôt que de reproduire une douleur qui n’est pas là."}$j$::jsonb,
   $t$Quand aucun mouvement ne modifie la douleur et qu’aucun test ne la reproduit, la question n’est plus quel tissu traiter mais si l’on est encore dans le champ mécanique. C’est le signal le plus fiable de tout le tri, et il ne demande aucun matériel.$t$, 7),

  -- 8. Radiculalgie L5 ------------------------------------------------------
  (v_module, 'radiculalgie-l5', $t$Radiculalgie L5 d’origine discale$t$, 'decouverte',
   $j${"prenom":"Thomas","age":38,"sexe":"homme","profession":"technicien de maintenance","motif":"Douleur qui part du dos et descend dans la jambe gauche depuis trois semaines","contexte":"Il arrive avec une attitude antalgique et évite de s’asseoir"}$j$::jsonb,
   $j${"histoire":"Lumbago il y a trois semaines en déplaçant une machine. Au bout de quatre jours, la douleur est descendue dans la jambe gauche et le dos lui fait moins mal qu’avant.","douleur":"Trajet précis : fesse, face postéro-externe de cuisse, côté externe du mollet, dessus du pied, jusqu’au gros orteil. 7 sur 10 dans la jambe. Fourmillements sur le dessus du pied.","aggravants":"La position assise, la voiture, la toux, l’éternuement.","soulageants":"Marcher un peu, être debout, allongé sur le côté avec un coussin entre les genoux.","antecedents":"Deux épisodes de lombalgie sans irradiation. Rien d’autre.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer, pas de problème pour uriner ou aller à la selle, pas d’engourdissement du périnée.","vecu":"Il a lu que les hernies discales s’opèrent et il a peur de finir au bloc. Il a arrêté le sport et bouge le moins possible.","a_ne_pas_dire_spontanement":"Sa crainte de l’opération ne sort que si on lui demande ce qu’il pense de sa douleur."}$j$::jsonb,
   $j${"slr":"Positif à gauche à 35 degrés, avec reproduction exacte de la douleur de jambe. Négatif à droite.","slump":"Positif à gauche, la douleur diminue à la remise en extension cervicale.","neuro_force":"Extension de l’hallux gauche cotée à 4 sur 5, stable selon le patient depuis une semaine. Reste du testing normal.","neuro_sensibilite":"Hypoesthésie du dessus du pied gauche et du premier espace interdigital.","neuro_reflexes":"Réflexes présents et symétriques.","dn4":"Score 5 sur 10 : composante neuropathique probable.","perine":"Mictions et selles normales, pas d’anesthésie en selle.","repetes_extension":"La douleur de mollet remonte vers la fesse après dix répétitions, et le dos devient un peu plus douloureux."}$j$::jsonb,
   $j${"issue":"fin_radiculalgie","tableau":"Radiculalgie L5 gauche, mécanisme neuropathique, sans déficit sévère","elements":["Trajet systématisé L5 avec paresthésies du même territoire","Déficit moteur modéré et stable","Tests neurodynamiques positifs et concordants","Absence de signe de queue de cheval"],"examens_cles":["slr","neuro_force","neuro_sensibilite","perine"],"piege":"Un déficit à 4 sur 5 fait hésiter. Ce qui compte n’est pas sa présence mais sa sévérité et son évolution d’une consultation à l’autre."}$j$::jsonb,
   $t$La majorité des radiculalgies discales s’améliorent nettement en six à douze semaines. Le rôle du thérapeute est de traiter, d’expliquer cette histoire naturelle à un patient qui redoute le bloc, et de surveiller le déficit à chaque séance avec une consigne écrite de queue de cheval.$t$, 8),

  -- 9. Sténose lombaire -----------------------------------------------------
  (v_module, 'stenose', $t$Sténose lombaire, claudication neurogène$t$, 'intermediaire',
   $j${"prenom":"Simone","age":72,"sexe":"femme","profession":"retraitée","motif":"Elle ne peut plus marcher plus de dix minutes sans devoir s’arrêter","contexte":"Elle est venue avec sa fille, qui fait les courses à sa place"}$j$::jsonb,
   $j${"histoire":"Gêne installée depuis deux ans, aggravée depuis six mois. Le périmètre de marche diminue régulièrement.","douleur":"Lourdeur et brûlure des deux cuisses et des deux mollets à la marche, avec des fourmillements. Le dos lui-même la gêne peu.","aggravants":"Marcher, surtout en terrain plat et en descente. Rester debout longtemps.","soulageants":"S’asseoir, et surtout se pencher en avant. Elle peut faire ses courses sans problème en poussant un caddie. Elle fait du vélo d’appartement vingt minutes sans aucune gêne.","antecedents":"Hypertension, arthrose des genoux. Pas de tabac.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble urinaire nouveau.","vecu":"Elle pense que c’est l’âge et que rien ne peut être fait.","a_ne_pas_dire_spontanement":"Le soulagement par le caddie et la tolérance du vélo ne sortent que si on interroge précisément ce qui soulage."}$j$::jsonb,
   $j${"marche":"Apparition d’une lourdeur des deux jambes après sept minutes de marche, disparaissant en deux minutes uniquement en position assise ou penchée en avant.","pouls":"Pouls fémoraux, poplités et pédieux présents et symétriques. Abdomen souple.","repetes_flexion":"Soulagement net des symptômes de jambes après dix répétitions en flexion.","repetes_extension":"Reproduction des symptômes de jambes après six répétitions.","neuro_reflexes":"Réflexes achilléens diminués des deux côtés, de façon symétrique.","hanche_amplitudes":"Rotation interne à 30 degrés des deux côtés, légèrement douloureuse en fin d’amplitude.","mobilite_active":"Extension limitée et reproduisant la gêne de jambes, flexion libre et soulageante."}$j$::jsonb,
   $j${"issue":"fin_stenose","tableau":"Sténose lombaire dégénérative avec claudication neurogène","elements":["Symptômes bilatéraux de membres inférieurs à la marche après 60 ans","Soulagement par la flexion et par la position assise","Vélo bien toléré","Pouls périphériques présents"],"examens_cles":["marche","pouls","repetes_flexion"],"piege":"À cet âge, une claudication vasculaire donne un tableau proche. Ce sont les pouls et le comportement en flexion qui séparent les deux, et les deux peuvent coexister."}$j$::jsonb,
   $t$Le soulagement par la flexion est le fil conducteur : le caddie, le vélo, la position assise. Prendre les pouls reste obligatoire, parce que les deux claudications coexistent souvent et que trouver l’une n’autorise pas à écarter l’autre.$t$, 9),

  -- 10. Claudication vasculaire --------------------------------------------
  (v_module, 'claudication-vasculaire', $t$Claudication artérielle des membres inférieurs$t$, 'expert',
   $j${"prenom":"Alain","age":66,"sexe":"homme","profession":"retraité, ancien peintre en bâtiment","motif":"Douleur des mollets à la marche, qu’il attribue à son dos","contexte":"Il fume un paquet par jour depuis quarante ans"}$j$::jsonb,
   $j${"histoire":"Gêne apparue il y a un an, stable dans son intensité mais toujours présente. Un confrère lui a parlé de canal lombaire rétréci.","douleur":"Crampe des deux mollets à la marche, surtout à droite, sans douleur lombaire notable.","aggravants":"La marche, toujours après la même distance, environ deux cents mètres. C’est pire en montée.","soulageants":"S’arrêter et rester debout. En deux ou trois minutes, c’est passé, sans avoir besoin de s’asseoir ni de se pencher.","antecedents":"Tabac, hypertension, diabète de type 2, cholestérol. Un stent coronaire il y a quatre ans.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer.","vecu":"Il veut qu’on lui ouvre le canal avec des manipulations.","a_ne_pas_dire_spontanement":"Le fait qu’il n’ait pas besoin de s’asseoir pour récupérer ne sort que si on demande précisément comment la douleur cède."}$j$::jsonb,
   $j${"pouls":"Pouls pédieux et tibiaux postérieurs abolis des deux côtés, pouls poplités diminués. Peau des jambes fine et dépilée, pas de masse battante.","marche":"Crampe des mollets reproduite à 190 mètres, cédant en deux minutes en station debout simple.","repetes_flexion":"Aucune modification des symptômes de jambes.","repetes_extension":"Aucune modification des symptômes de jambes.","mobilite_active":"Amplitudes lombaires conservées et peu douloureuses.","neuro_reflexes":"Réflexes présents et symétriques."}$j$::jsonb,
   $j${"issue":"fin_vasculaire","tableau":"Artériopathie oblitérante des membres inférieurs","elements":["Périmètre de marche reproductible","Récupération en station debout simple, sans avoir à s’asseoir ni à se pencher","Pouls distaux abolis","Terrain vasculaire majeur"],"examens_cles":["pouls","marche"],"piege":"Un confrère a déjà évoqué le canal lombaire, et le patient arrive avec ce diagnostic. La flexion ne change rien, et c’est ce qui doit alerter."}$j$::jsonb,
   $t$Trois éléments orientent vers l’artère et non vers le canal : un périmètre reproductible, une récupération rapide à l’arrêt debout simple, des pouls diminués ou abolis. Traiter ce patient comme une sténose lombaire, c’est retarder la prise en charge d’un risque cardiovasculaire majeur.$t$, 10),

  -- 11. Mécanisme nociplastique --------------------------------------------
  (v_module, 'nociplastique', $t$Lombalgie chronique, mécanisme nociplastique$t$, 'intermediaire',
   $j${"prenom":"Sandrine","age":41,"sexe":"femme","profession":"secrétaire médicale","motif":"Lombalgie permanente depuis deux ans, rien ne la soulage durablement","contexte":"Elle apporte un classeur d’examens et de comptes rendus"}$j$::jsonb,
   $j${"histoire":"Douleur installée depuis deux ans après un épisode de lombalgie aiguë. Depuis, elle n’a jamais complètement disparu. Elle a vu six praticiens.","douleur":"Lombaire basse, étendue aux deux fesses et à la ceinture, mal délimitée, 6 sur 10 en permanence avec des poussées à 9.","aggravants":"Tout finit par faire mal. Les journées difficiles, le stress, le manque de sommeil.","soulageants":"Rien ne dure. Les séances la soulagent une demi-journée.","antecedents":"Syndrome de l’intestin irritable, migraines, deux ans de sommeil haché. Fatigue permanente, difficultés de concentration.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble sphinctérien, pas de déficit.","vecu":"Son IRM montre une discopathie L5-S1 et elle est convaincue que son disque est usé et qu’il faut le remettre en place. Elle a peur de se pencher en avant.","a_ne_pas_dire_spontanement":"La fatigue, le sommeil et les troubles de concentration ne sortent que si on les demande."}$j$::jsonb,
   $j${"sensibilisation_centrale":"Allodynie au frottement sur toute la région lombaire et fessière, post-sensations après la palpation, hypersensibilité à la pression débordant largement la zone douloureuse.","start_back":"Score total 7 sur 9, sous-score psychosocial 4 sur 5 : risque élevé.","dn4":"Score 2 sur 10.","mobilite_active":"Flexion réalisée avec appréhension et en bloc, amplitudes conservées, douleur reproduite dans tous les plans.","repetes_extension":"Pas de modification de topographie, douleur globalement majorée après l’épreuve.","repetes_flexion":"Pas de modification de topographie, douleur globalement majorée après l’épreuve.","slr":"Tension postérieure de cuisse des deux côtés à 60 degrés, non concordante.","imagerie":"IRM apportée par la patiente : discopathie L5-S1 et protrusion non conflictuelle, sans rapport établi avec les symptômes."}$j$::jsonb,
   $j${"issue":"fin_nociplastique","tableau":"Lombalgie chronique à mécanisme nociplastique dominant","elements":["Douleur régionale diffuse depuis plus de trois mois","Hypersensibilité évoquée à l’examen, allodynie et post-sensations","Comorbidités de sommeil, de fatigue et de cognition","Absence de réponse directionnelle"],"examens_cles":["sensibilisation_centrale","start_back"],"piege":"L’IRM offre une explication toute prête, et la patiente y tient. Reprendre des séances passives sur un disque usé entretient exactement ce qu’il faut défaire."}$j$::jsonb,
   $t$Les critères 2021 sont réunis, hypersensibilité évoquée comprise. Enchaîner les séances passives entretient l’idée d’un tissu à réparer et le recours au soin. La reprise graduée se pilote sur la fonction, avec des objectifs écrits, et la thérapie manuelle reste un appoint bref et non répété.$t$, 11),

  -- 12. Préférence directionnelle en extension -----------------------------
  (v_module, 'preference-extension', $t$Préférence directionnelle en extension$t$, 'decouverte',
   $j${"prenom":"Julien","age":34,"sexe":"homme","profession":"commercial, six heures de voiture par jour","motif":"Lombalgie depuis huit jours, apparue après un long trajet","contexte":"Il se lève plusieurs fois pendant l’entretien"}$j$::jsonb,
   $j${"histoire":"Douleur apparue il y a huit jours au cours d’un déplacement de six heures. Pas de traumatisme.","douleur":"Lombaire basse, un peu plus à droite, débordant sur la fesse droite, sans descendre sous le pli fessier. 6 sur 10.","aggravants":"La position assise prolongée, la voiture, se pencher en avant, le matin au réveil.","soulageants":"Marcher, se cambrer, être debout.","antecedents":"Deux épisodes semblables les trois dernières années, résolus en deux semaines.","drapeaux":"Rien de particulier : pas de fièvre, pas de perte de poids, pas de cancer, pas de trouble sphinctérien.","vecu":"Il n’est pas inquiet, il veut juste que cela aille plus vite et il continue à travailler.","a_ne_pas_dire_spontanement":"Le soulagement en se cambrant n’est mentionné que si on demande ce qui soulage."}$j$::jsonb,
   $j${"repetes_extension":"Après dix répétitions, la douleur fessière disparaît et se recentre en région lombaire médiane. Amplitude améliorée, patient surpris du changement.","repetes_flexion":"Après cinq répétitions, la douleur redescend vers la fesse et l’amplitude diminue.","mobilite_active":"Flexion limitée et douloureuse avec déviation latérale droite, extension limitée en début de test.","slr":"Négatif des deux côtés.","start_back":"Score total 2 sur 9 : risque faible."}$j$::jsonb,
   $j${"issue":"fin_extension","tableau":"Lombalgie avec préférence directionnelle en extension","elements":["Douleur ne dépassant pas le pli fessier","Aggravation par la position assise et la flexion","Centralisation obtenue en extension répétée"],"examens_cles":["repetes_extension","repetes_flexion"],"piege":"Le tableau est simple, à condition d’avoir fait les mouvements répétés. Sans eux, on se rabat sur la technique habituelle."}$j$::jsonb,
   $t$La centralisation est le signe dont la valeur pronostique est la mieux établie de tout l’examen lombaire, et il donne le traitement du soir même. Encore faut-il faire l’épreuve : dix répétitions dans une direction, réévaluation immédiate.$t$, 12),

  -- 13. Préférence directionnelle en flexion -------------------------------
  (v_module, 'preference-flexion', $t$Préférence directionnelle en flexion$t$, 'intermediaire',
   $j${"prenom":"Martine","age":58,"sexe":"femme","profession":"coiffeuse","motif":"Lombalgie basse depuis trois semaines, surtout en fin de journée debout","contexte":"Elle travaille debout huit heures par jour"}$j$::jsonb,
   $j${"histoire":"Douleur installée progressivement depuis trois semaines, sans événement déclenchant.","douleur":"Lombaire basse et médiane, parfois sur les deux fesses, 5 sur 10, sans descendre sous les fesses.","aggravants":"Rester debout, se cambrer, la fin de journée au travail.","soulageants":"S’asseoir, se pencher en avant, se mettre en chien de fusil.","antecedents":"Deux grossesses, rien d’autre. Pas de tabac.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble sphinctérien.","vecu":"Elle a entendu qu’il ne fallait surtout pas arrondir le dos et elle évite de se pencher, ce qui la gêne beaucoup au travail.","a_ne_pas_dire_spontanement":"Elle ne dit pas spontanément qu’elle marche sans limitation : il faut le demander."}$j$::jsonb,
   $j${"repetes_flexion":"Après dix répétitions en décubitus, la douleur fessière disparaît et se concentre en lombaire médiane, l’amplitude debout est améliorée.","repetes_extension":"Après six répétitions, la douleur s’étend aux deux fesses et devient plus intense.","marche":"Vingt minutes de marche sans apparition de symptôme de membre inférieur.","mobilite_active":"Extension limitée et douloureuse, flexion complète et soulageante.","pouls":"Pouls présents et symétriques."}$j$::jsonb,
   $j${"issue":"fin_flexion","tableau":"Lombalgie avec préférence directionnelle en flexion","elements":["Aggravation en station debout et en extension","Soulagement en flexion et en position assise","Centralisation obtenue en flexion répétée","Marche non limitée, ce qui écarte la claudication"],"examens_cles":["repetes_flexion","repetes_extension","marche"],"piege":"Une minorité de patients centralise en flexion, et l’a priori pousse à prescrire de l’extension. Chez une patiente de cet âge soulagée par la flexion, il faut aussi vérifier la marche pour ne pas manquer une sténose débutante."}$j$::jsonb,
   $t$Une minorité de patients centralise en flexion. Le test tranche, l’a priori se trompe régulièrement. Chez le sujet de plus de 55 ans soulagé par la flexion, l’épreuve de marche est ce qui sépare une préférence directionnelle d’une claudication neurogène débutante.$t$, 13),

  -- 14. Ceinture pelvienne --------------------------------------------------
  (v_module, 'ceinture-pelvienne', $t$Douleur de ceinture pelvienne$t$, 'intermediaire',
   $j${"prenom":"Léa","age":33,"sexe":"femme","profession":"infirmière, en reprise après congé maternité","motif":"Douleur de la fesse gauche depuis la grossesse, cinq mois après l’accouchement","contexte":"Elle porte son bébé sur la hanche gauche pendant l’entretien"}$j$::jsonb,
   $j${"histoire":"Douleur apparue au sixième mois de grossesse, non résolue cinq mois après l’accouchement. Elle pensait que cela partirait tout seul.","douleur":"Fesse gauche basse, juste sous la crête, irradiant parfois à l’arrière de la cuisse sans dépasser le genou. 6 sur 10.","aggravants":"Se retourner dans le lit, monter les escaliers, rester debout sur une jambe, porter son bébé.","soulageants":"S’allonger. La ceinture de grossesse la soulageait beaucoup, elle ne la met plus.","antecedents":"Une grossesse, accouchement par voie basse. Pas d’autre antécédent.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer, pas de trouble urinaire.","vecu":"Elle a lu que son bassin s’était déplacé et voudrait qu’on le remette droit.","a_ne_pas_dire_spontanement":"Le soulagement apporté par la ceinture ne sort que si on demande ce qui soulage."}$j$::jsonb,
   $j${"cluster_laslett":"Quatre tests sur cinq positifs à gauche, dont la distraction et le thigh thrust, avec reproduction de la douleur habituelle.","aslr":"Soulèvement du membre gauche coté difficile, nettement amélioré sous compression pelvienne manuelle.","repetes_extension":"Aucune modification de la douleur fessière.","repetes_flexion":"Aucune modification de la douleur fessière.","slr":"Négatif des deux côtés.","mobilite_active":"Amplitudes lombaires complètes et non douloureuses.","palper_rouler":"Pli cutané comparable des deux côtés."}$j$::jsonb,
   $j${"issue":"fin_ceinture","tableau":"Douleur de ceinture pelvienne du post-partum","elements":["Douleur apparue pendant la grossesse et persistante","Douleur de transfert de charge : lit, escaliers, appui unipodal","Cluster de Laslett positif après avoir écarté l’origine lombaire","ASLR amélioré par la compression pelvienne"],"examens_cles":["cluster_laslett","aslr","repetes_extension"],"piege":"La patiente demande un bassin remis droit. Les tests de position et de mobilité sacro-iliaque ne servent pas à décider, seuls les tests de provocation ont été validés contre bloc anesthésique."}$j$::jsonb,
   $t$Le cluster de Laslett n’a de valeur qu’après avoir écarté une origine lombaire, ce que font les mouvements répétés. C’est le seul ensemble lombo-pelvien validé contre bloc anesthésique, et l’ASLR sous compression donne en prime l’argument pour la ceinture.$t$, 14),

  -- 15. Syndrome de Maigne --------------------------------------------------
  (v_module, 'maigne', $t$Syndrome de la charnière thoraco-lombaire$t$, 'expert',
   $j${"prenom":"Patrick","age":47,"sexe":"homme","profession":"carreleur","motif":"Douleur de la crête iliaque droite depuis deux mois, traitée sans succès","contexte":"Il a déjà fait dix séances centrées sur le bas du dos"}$j$::jsonb,
   $j${"histoire":"Douleur installée depuis deux mois, sans traumatisme. Dix séances de thérapie manuelle sur la région lombaire basse n’ont rien donné.","douleur":"Le long de la crête iliaque droite et du pli de l’aine, parfois sur la fesse haute. 5 sur 10, permanente en fin de journée.","aggravants":"Les positions prolongées, le travail au sol, la ceinture du pantalon qui appuie.","soulageants":"Rien de net.","antecedents":"Lombalgies épisodiques anciennes. Pas d’antécédent médical.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer, pas de trouble sphinctérien.","vecu":"Il commence à penser qu’on ne trouvera jamais et qu’il faudra vivre avec.","a_ne_pas_dire_spontanement":"Il ne dit pas spontanément que la douleur est déclenchée par la pression de la ceinture."}$j$::jsonb,
   $j${"palper_rouler":"Pli cutané nettement épaissi et douloureux à droite, sur la crête iliaque et la fesse haute, asymétrie franche par rapport à la gauche.","articulaires_tl":"Pression douloureuse et reproductrice des articulaires postérieures droites de T12 et L1.","point_cluneal":"Sensibilité diffuse de la crête sans point exquis reproduisant la douleur irradiée.","cluster_laslett":"Aucun des cinq tests ne reproduit la douleur habituelle.","repetes_extension":"Aucune modification de la topographie.","repetes_flexion":"Aucune modification de la topographie.","pa_segmentaires":"Pressions lombaires basses peu douloureuses, contrastant avec la sensibilité de la charnière."}$j$::jsonb,
   $j${"issue":"fin_maigne","tableau":"Syndrome de la charnière thoraco-lombaire, dérangement T12-L1 droit","elements":["Douleur de crête iliaque et d’aine, sans origine lombaire basse retrouvée","Palper-rouler franchement asymétrique","Pression douloureuse des articulaires T12-L1","Échec des traitements centrés sur le rachis lombaire bas"],"examens_cles":["palper_rouler","articulaires_tl"],"piege":"La douleur est montrée en bas, et l’étage responsable est au-dessus. Dix séances au mauvais endroit, c’est le scénario typique de ce syndrome."}$j$::jsonb,
   $t$C’est exactement pour cela que ces patients sont étiquetés résistants : on traite l’étage où ils montrent leur douleur. Le palper-rouler asymétrique et la pression des articulaires T12-L1 prennent trente secondes et redirigent tout le traitement.$t$, 15),

  -- 16. Névralgie clunéale --------------------------------------------------
  (v_module, 'cluneal', $t$Névralgie des nerfs clunéaux supérieurs$t$, 'expert',
   $j${"prenom":"Françoise","age":52,"sexe":"femme","profession":"agent d’entretien","motif":"Douleur très localisée sur le haut de la fesse droite depuis quatre mois","contexte":"Elle pose le doigt sur un point précis pour montrer où elle a mal"}$j$::jsonb,
   $j${"histoire":"Douleur apparue il y a quatre mois, sans cause. Elle peut la montrer avec un doigt, toujours au même endroit.","douleur":"Point précis sur la crête iliaque droite, avec une irradiation vers la fesse et parfois la face postérieure de cuisse, sans dépasser le genou. 6 sur 10.","aggravants":"Rester assise sur une chaise dure, se pencher, la ceinture de son pantalon de travail, l’appui du dossier de la voiture.","soulageants":"Se mettre debout, changer d’appui.","antecedents":"Rien de particulier. Pas de chirurgie, pas de prise de greffon iliaque.","drapeaux":"Pas de fièvre, pas de perte de poids, pas de cancer, pas de trouble sphinctérien.","vecu":"Elle craint une sciatique et se demande si elle va pouvoir continuer son travail.","a_ne_pas_dire_spontanement":"Le lien avec la ceinture et l’appui du dossier ne sort que si on demande ce qui déclenche."}$j$::jsonb,
   $j${"point_cluneal":"Point exquis sur la crête iliaque droite, à environ 7 centimètres de la ligne médiane. La pression reproduit exactement la douleur habituelle, irradiation fessière comprise.","palper_rouler":"Pli cutané comparable des deux côtés, pas d’asymétrie.","articulaires_tl":"Pression non douloureuse des articulaires T12 et L1.","cluster_laslett":"Aucun test positif.","slr":"Négatif des deux côtés.","repetes_extension":"Aucune modification de la topographie.","repetes_flexion":"Aucune modification de la topographie.","neuro_sensibilite":"Hypoesthésie discrète de la région fessière haute droite."}$j$::jsonb,
   $j${"issue":"fin_cluneal","tableau":"Névralgie des nerfs clunéaux supérieurs à droite","elements":["Douleur montrée du doigt, toujours au même point de la crête","Reproduction exacte de la douleur, irradiation comprise, à la pression du point","Aggravation par les appuis et par la ceinture","Charnière thoraco-lombaire et sacro-iliaque non contributives"],"examens_cles":["point_cluneal","palper_rouler","cluster_laslett"],"piege":"Le tableau ressemble à une sciatique tronquée. Ce qui le signe est la précision du point et la reproduction de l’irradiation, pas une simple sensibilité locale."}$j$::jsonb,
   $t$Le signe distinctif est la précision du point : la pression reproduit la douleur habituelle, irradiation comprise, et pas une simple sensibilité locale. C’est aussi ce qui le distingue du syndrome de la charnière, dont le palper-rouler est asymétrique.$t$, 16),

  -- 17. Contrôle du mouvement ----------------------------------------------
  (v_module, 'controle-moteur', $t$Instabilité clinique, profil contrôle du mouvement$t$, 'intermediaire',
   $j${"prenom":"Camille","age":29,"sexe":"femme","profession":"professeure de yoga","motif":"Lombalgies à répétition, cinq épisodes cette année","contexte":"Elle est très souple et le montre volontiers"}$j$::jsonb,
   $j${"histoire":"Épisodes de blocage lombaire récurrents depuis trois ans, cinq cette année, déclenchés par des gestes anodins. Entre les crises, tout va bien mais elle se sent instable.","douleur":"Lombaire basse et médiane, 4 sur 10 hors crise, 8 pendant. Pas d’irradiation.","aggravants":"Les positions prolongées, les gestes de bascule, se relever d’une flexion.","soulageants":"Bouger, changer de position, le gainage quand elle en fait.","antecedents":"Hypermobilité générale. Pas de maladie, pas de chirurgie.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble sphinctérien.","vecu":"Elle veut comprendre pourquoi cela revient et repartir avec quelque chose à faire, pas avec une séance de plus.","a_ne_pas_dire_spontanement":"La sensation d’instabilité et de dérobement ne sort que si on demande ce qu’elle ressent entre les crises."}$j$::jsonb,
   $j${"mouvements_aberrants":"Arc douloureux au retour de flexion, appui des mains sur les cuisses pour se redresser, phénomène de bascule visible.","pit":"Positif : la douleur provoquée par la pression postéro-antérieure disparaît lors du soulèvement actif des jambes.","slr":"Amplitude à 100 degrés des deux côtés, sans douleur ni reproduction.","mobilite_active":"Amplitudes très importantes dans tous les plans, contrôle du retour de flexion médiocre.","repetes_extension":"Pas de modification de la topographie.","repetes_flexion":"Pas de modification de la topographie.","start_back":"Score total 3 sur 9 : risque faible."}$j$::jsonb,
   $j${"issue":"fin_controle_moteur","tableau":"Instabilité clinique lombaire, règle de Hicks à 4 items sur 4","elements":["Âge inférieur à 40 ans","Élévation de jambe tendue au-delà de 91 degrés","Mouvements aberrants au retour de flexion","Test d’instabilité en procubitus positif"],"examens_cles":["mouvements_aberrants","pit","slr"],"piege":"Les épisodes sont récurrents et calmés par une manipulation, ce qui incite à la répéter. La règle de Hicks désigne ici un autre traitement, et c’est la sélection du patient qui fait la différence."}$j$::jsonb,
   $t$Les exercices de stabilisation ne battent pas un autre exercice actif : c’est la sélection du patient, par la règle de Hicks ou par ce qui l’empêche de bouger, qui fait la différence. Ici les quatre items sont réunis, ce qui est rare et net.$t$, 17),

  -- 18. Optimisation fonctionnelle -----------------------------------------
  (v_module, 'optimisation', $t$Profil optimisation fonctionnelle$t$, 'decouverte',
   $j${"prenom":"Kévin","age":31,"sexe":"homme","profession":"déménageur et rugbyman amateur","motif":"Il n’a plus mal depuis six semaines mais n’ose pas reprendre","contexte":"Il vient pour un feu vert avant la reprise du championnat"}$j$::jsonb,
   $j${"histoire":"Lombalgie aiguë il y a trois mois en portant une armoire. Douleur résolue depuis six semaines. Il n’a rien repris, ni le travail lourd ni le rugby.","douleur":"Plus aucune douleur au quotidien. Une gêne sourde quand il force un peu, qui passe en quelques heures.","aggravants":"Rien au quotidien. Les charges lourdes lui font peur.","soulageants":"Sans objet.","antecedents":"Un seul épisode de lombalgie, celui-ci.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble sphinctérien, pas de déficit.","vecu":"Il n’est pas inquiet pour sa douleur, il doute de sa capacité à encaisser un plaquage et un mois de déménagements.","a_ne_pas_dire_spontanement":"Le fait qu’il n’ait fait aucun renforcement depuis trois mois ne sort que si on demande ce qu’il a fait pendant cette période."}$j$::jsonb,
   $j${"mobilite_active":"Amplitudes complètes, indolores dans tous les plans.","mouvements_aberrants":"Retour de flexion régulier, pas d’arc douloureux.","slr":"Négatif des deux côtés, amplitude 80 degrés.","neuro_force":"Force cotée à 5 sur 5 partout, mais endurance des extenseurs du tronc très diminuée : tenue de Sorensen à 38 secondes.","start_back":"Score total 1 sur 9 : risque faible.","repetes_extension":"Aucune douleur, aucune modification.","repetes_flexion":"Aucune douleur, aucune modification."}$j$::jsonb,
   $j${"issue":"fin_optimisation","tableau":"Fin d’épisode avec capacité insuffisante pour la demande","elements":["Douleur résolue depuis six semaines","Aucune reprise de charge depuis trois mois","Endurance des extenseurs effondrée","Demande professionnelle et sportive élevée"],"examens_cles":["neuro_force","start_back","mobilite_active"],"piege":"Il n’y a plus rien à traiter, et c’est exactement le moment où l’on arrête. La consultation ne sert à rien si elle se termine par un feu vert sans programme."}$j$::jsonb,
   $t$C’est l’étape la plus souvent escamotée. On arrête quand la douleur a cédé, c’est-à-dire au moment précis où commence le travail qui réduit les récidives. Le critère de sortie n’est pas l’absence de douleur, c’est une capacité qui dépasse la demande, avec une marge.$t$, 18),

  -- 19. Candidat à la manipulation -----------------------------------------
  (v_module, 'manipulation-flynn', $t$Lombalgie aiguë, règle de Flynn favorable$t$, 'decouverte',
   $j${"prenom":"Aurélie","age":36,"sexe":"femme","profession":"comptable","motif":"Lombalgie depuis cinq jours, apparue en sortant du lit","contexte":"Elle travaille normalement et n’est pas arrêtée"}$j$::jsonb,
   $j${"histoire":"Douleur apparue il y a cinq jours en se levant, sans effort. Stable depuis, plutôt en amélioration lente.","douleur":"Lombaire basse gauche, 5 sur 10, sans irradiation, elle ne descend jamais sous la fesse.","aggravants":"Les changements de position, le premier pas après être restée assise.","soulageants":"La marche, la chaleur.","antecedents":"Un épisode similaire il y a quatre ans, résolu en trois semaines.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble sphinctérien, pas de fourmillement.","vecu":"Elle n’a pas peur de bouger, elle continue son sport et son travail, elle veut juste que cela aille plus vite.","a_ne_pas_dire_spontanement":"Rien de caché dans ce cas : l’enjeu est de reconnaître un tableau favorable et de ne pas le compliquer."}$j$::jsonb,
   $j${"pa_segmentaires":"Hypomobilité segmentaire nette en L4-L5 gauche, reproduisant la douleur habituelle. Étages voisins mobiles.","hanche_amplitudes":"Rotation interne à 45 degrés à gauche et 42 degrés à droite, indolores.","start_back":"Score total 2 sur 9, sous-score psychosocial 0 sur 5 : risque faible. FABQ-Travail à 12.","slr":"Négatif des deux côtés.","neuro_force":"Force normale et symétrique.","repetes_extension":"Amélioration modeste de l’amplitude, pas de changement de topographie.","mobilite_active":"Flexion et inclinaison gauche limitées en fin d’amplitude, douleur locale sans irradiation."}$j$::jsonb,
   $j${"issue":"fin_manipulation","tableau":"Lombalgie aiguë non spécifique, cinq critères de Flynn sur cinq","elements":["Durée inférieure à 16 jours","Aucun symptôme sous le genou","FABQ-Travail inférieur à 19","Au moins un segment hypomobile","Au moins une hanche à plus de 35 degrés de rotation interne"],"examens_cles":["pa_segmentaires","hanche_amplitudes","start_back"],"piege":"Il faut chercher les cinq items, y compris la rotation interne de hanche, que personne ne mesure spontanément dans une lombalgie."}$j$::jsonb,
   $t$La règle de Flynn est une règle de réponse au traitement, pas un diagnostic. Elle hiérarchise une première intention, elle ne promet pas un résultat, et la recommandation pose une condition : la manipulation s’inscrit dans un programme qui comprend de l’exercice.$t$, 19),

  -- 20. Mobilisation plutôt que manipulation -------------------------------
  (v_module, 'mobilisation', $t$Lombalgie très irritable sur terrain ostéoporotique$t$, 'intermediaire',
   $j${"prenom":"Jacqueline","age":69,"sexe":"femme","profession":"retraitée, ancienne libraire","motif":"Lombalgie depuis six jours, très douloureuse au moindre mouvement","contexte":"Elle se déplace à petits pas et redoute qu’on la touche"}$j$::jsonb,
   $j${"histoire":"Douleur apparue il y a six jours en jardinant, sans chute ni choc. Elle reste forte mais s’améliore un peu depuis deux jours.","douleur":"Lombaire basse, en barre, 7 sur 10, sans irradiation sous la fesse.","aggravants":"Presque tous les mouvements. Il lui faut cinq minutes pour se lever d’une chaise.","soulageants":"Rester allongée, la chaleur. La douleur met longtemps à redescendre après un mouvement.","antecedents":"Ostéoporose densitométrique connue, traitée depuis trois ans. Pas de fracture connue. Pas de corticoïdes. Hypertension.","drapeaux":"Pas de perte de poids, pas de fièvre, pas de cancer, pas de trouble sphinctérien. Pas de chute.","vecu":"Une amie s’est fait manipuler et en garde un mauvais souvenir. Elle dit clairement qu’elle ne veut pas être craquée.","a_ne_pas_dire_spontanement":"L’ostéoporose est dite si on interroge les antécédents ; le refus de la manipulation est dit spontanément si on évoque le traitement."}$j$::jsonb,
   $j${"palpation_epineuses":"Sensibilité diffuse des masses paravertébrales, percussion des épineuses indolore, pas de point exquis.","pa_segmentaires":"Pressions très douloureuses dès le contact, douleur qui met plusieurs secondes à redescendre : irritabilité élevée.","mobilite_active":"Toutes les amplitudes limitées par la douleur, sans direction préférentielle nette.","repetes_extension":"Épreuve mal tolérée, interrompue après quatre répétitions, pas de changement de topographie.","repetes_flexion":"Épreuve mal tolérée, pas de changement de topographie.","slr":"Négatif des deux côtés.","neuro_force":"Force normale et symétrique.","drapeaux_rouges":"Ostéoporose connue et traitée, âge supérieur à 65 ans, mais pas de traumatisme, pas de corticothérapie, pas de perte de taille récente, percussion indolore."}$j$::jsonb,
   $j${"issue":"fin_mobilisation","tableau":"Lombalgie aiguë très irritable, haute vélocité non retenue","elements":["Irritabilité élevée : douleur longue à redescendre après la sollicitation","Terrain ostéoporotique","Refus explicite de la manipulation","Absence de critères de Flynn suffisants"],"examens_cles":["pa_segmentaires","drapeaux_rouges","palpation_epineuses"],"piege":"Le tableau est mécanique et bénin, et la tentation est de manipuler. Trois éléments s’y opposent, dont un que la patiente énonce elle-même."}$j$::jsonb,
   $t$Aucune supériorité nette de la haute vélocité sur la basse n’est établie dans la lombalgie. Le choix se fait sur l’irritabilité, le terrain et l’appréhension, et ici les trois pointent dans la même direction. Passer outre le refus d’une patiente n’est pas un choix technique.$t$, 20);

  -- Vérification, dans la transaction : une conclusion attendue qui ne serait
  -- pas une feuille de l'arbre rendrait le cas incorrigeable, et le simulateur
  -- proposerait une réponse impossible à choisir. Mieux vaut que la migration
  -- échoue que de laisser passer cela.
  SELECT a.payload -> 'noeuds' INTO v_noeuds
    FROM public.region_chapter_activities a
    JOIN public.region_chapters c ON c.id = a.chapter_id
   WHERE c.module_id = v_module AND a.kind = 'arbre_decision'
   LIMIT 1;

  IF v_noeuds IS NULL THEN
    RAISE EXCEPTION 'Arbre de décision absent du parcours : appliquer d''abord la migration region_arbre_decision';
  END IF;

  SELECT string_agg(DISTINCT s.expected ->> 'issue', ', ') INTO v_orphelin
    FROM public.region_simulation_cases s
   WHERE s.module_id = v_module
     AND (v_noeuds -> (s.expected ->> 'issue') ->> 'type') IS DISTINCT FROM 'conclusion';

  IF v_orphelin IS NOT NULL THEN
    RAISE EXCEPTION 'Conclusion attendue absente des feuilles de l''arbre : %', v_orphelin;
  END IF;

END $do$;
